@url = http://localhost:3000/api/viajes


###Obtener viajes
GET {{url}}

###Obtener por id
GET {{url}}/1
###Crear viajes
POST {{url}}
Content-Type: application/json

{
    "vehiculo_id": 5,
    "conductor_id": 2,
    "fecha_salida": "2025-10-26",
    "fecha_llegada": "2025-10-28",
    "origen": "tucuman",
    "destino": "salta",
    "kilometros": 2000,
    "observaciones": "reservado"
}


###Actualizar viajes
PUT {{url}}/8
Content-Type: application/json

{
    "vehiculo_id": 5,
    "conductor_id": 2,
    "fecha_salida": "2025-10-26",
    "fecha_llegada": "2025-10-28",
    "origen": "chubut",
    "destino": "salta",
    "kilometros": 4000,
    "observaciones": "reservado"
}

###Eliminar viajes
DELETE {{url}}/1
