@url = http://localhost:3000/api/vehiculos


###Ob###tener vehiculos
GET {{url}}

###Obtener por id
GET {{url}}/1
###Crear vehiculos
POST {{url}}
Content-Type: application/json

{
    "marca": "volkswagen",
    "modelo": "polotrack",
    "patente": "bcda",
    "año": 2024,
    "capacidad": 195
}

###Actualizar vehiculos
PUT {{url}}/1
Content-Type: application/json

{
    "marca": "Toyota",
    "modelo": "yaris",
    "patente": "abcd",
    "año": 2023,
    "capacidad": 500
}

###Eliminar vehiculos
DELETE {{url}}/7
