@url = http://localhost:3000/api/usuarios


###Obtener usuarios
GET {{url}}

###Obtener por id
GET {{url}}/1
###Crear usuarios
POST {{url}}
Content-Type: application/json

{
    "nombre": "MarioLuis",
    "email": "luispaes@hotmail.com",
    "password": "Hola444!."
}

###Actualizar usuarios
PUT {{url}}/3
Content-Type: application/json

{
    "nombre": "Marcos",
    "email": "marcos@gmail.com",
    "password": "HoLa!1040"
}
###Eliminar usuarios
DELETE {{url}}/0
