@url = http://localhost:3000/api/usuarios


###Obtener usuarios
GET {{url}}

###Obtener por id
GET {{url}}/1
###Crear usuarios
POST {{url}}
Content-Type: application/json

{
    "nombre": "Mario",
    "email": "lpaes@hotmail.com",
    "password": "Hola4444"
}

###Actualizar usuarios
PUT {{url}}/1
Content-Type: application/json

{
    "nombre": "Mauro",
    "email": "mauro@oulook.com",
    "password_hash": "Hola4444"
}
###Eliminar usuarios
DELETE {{url}}/0
